# Tensorflow

In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

1.8.0


In [3]:
hello = tf.constant("Hello")

In [4]:
world = tf.constant("World")

In [5]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [6]:
print(hello)

Tensor("Const:0", shape=(), dtype=string)


In [10]:
with tf.Session() as sess:
    result = sess.run(hello+world)


In [11]:
result

b'HelloWorld'

In [12]:
a = tf.constant(10)
b = tf.constant(20)

In [13]:
a+b

<tf.Tensor 'add_4:0' shape=() dtype=int32>

In [14]:
a+b

<tf.Tensor 'add_5:0' shape=() dtype=int32>

In [15]:
with tf.Session() as sess:
    result = sess.run(a+b)

In [16]:
result

30

In [17]:
const = tf.constant(10)

In [18]:
fill_mat = tf.fill((4,4),10)

In [26]:
myzeros = tf.zeros((4,4))

In [22]:
myones = tf.ones((4,4))

In [23]:
myrandn = tf.random_normal((4,4),mean = 0 , stddev = 1.0)

In [24]:
myrandu = tf.random_uniform((4,4),minval = 0, maxval = 1)

In [27]:
my_ops = [const, fill_mat, myzeros, myones, myrandn, myrandn]

In [28]:
sess = tf.InteractiveSession()

In [31]:
for op in my_ops:
    print(sess.run(op))
     

10
[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[ 1.8578317  -0.4752537   0.3426377   0.5242701 ]
 [ 0.15826459  0.10674109  1.3346132   0.83146745]
 [-0.5632513   0.4563187   0.5191648  -1.3559375 ]
 [ 0.17374195  1.2771764   0.6743334   1.1020387 ]]
[[ 0.8280493  -0.12059662  1.9781371   0.29351377]
 [ 0.28354865 -0.27622846 -0.09529198  0.45036364]
 [-0.51032275  1.6912423  -0.3122564   0.79686004]
 [-0.93231213  1.4841461   1.4543456  -0.63177216]]


In [39]:
a = tf.constant([ [1,2],
                  [3,4] ] ),

In [40]:
b = tf.constant([[10],[100]])

In [41]:
result = tf.matmul(a,b)

ValueError: Shape must be rank 2 but is rank 3 for 'MatMul_1' (op: 'MatMul') with input shapes: [1,2,2], [2,1].